// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type _404DocumentDataSlicesSlice = HeroErrorSlice;

/**
 * Content for 404 documents
 */
interface _404DocumentData {
  /**
   * Slice Zone field in *404*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<_404DocumentDataSlicesSlice> /**
   * Meta Title field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: 404.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: 404.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * 404 document from Prismic
 *
 * - **API ID**: `404`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type _404Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<_404DocumentData>, "404", Lang>;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.txt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  txt: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Text field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.txt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  txt: prismic.KeyTextField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HeroHomeSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type LandingDocumentDataSlicesSlice = never;

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice> /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never> /**
   * Logo field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/image
   */;
  logo: prismic.ImageField<never>;

  /**
   * Link field in *Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.lnk
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  lnk: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA field in *Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  > /**
   * Primary color field in *Landing*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary_color
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/color
   */;
  primary_color: prismic.ColorField;

  /**
   * Secondary color field in *Landing*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.secondary_color
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  secondary_color: prismic.ColorField;

  /**
   * Font field in *Landing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inter
   * - **API ID Path**: landing.font
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  font: prismic.SelectField<"Inter" | "Helvetica", "filled">;

  /**
   * Button style field in *Landing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Square
   * - **API ID Path**: landing.button_style
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_style: prismic.SelectField<
    "Square" | "Medium rounded" | "Rounded",
    "filled"
  >;
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

type LegalsDocumentDataSlicesSlice = never;

/**
 * Content for Legals documents
 */
interface LegalsDocumentData {
  /**
   * Slice Zone field in *Legals*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LegalsDocumentDataSlicesSlice> /**
   * Meta Title field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legals.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legals.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legals document from Prismic
 *
 * - **API ID**: `legals`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalsDocumentData>, "legals", Lang>;

/**
 * Item in *Redirect → Redirect*
 */
export interface RedirectDocumentDataRedirectItem {
  /**
   * Source field in *Redirect → Redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lang/page
   * - **API ID Path**: redirect.redirect[].source
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  source: prismic.KeyTextField;

  /**
   * Destination field in *Redirect → Redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lang/page
   * - **API ID Path**: redirect.redirect[].destination
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  destination: prismic.KeyTextField;
}

/**
 * Content for Redirect documents
 */
interface RedirectDocumentData {
  /**
   * Redirect field in *Redirect*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirect.redirect[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  redirect: prismic.GroupField<Simplify<RedirectDocumentDataRedirectItem>>;
}

/**
 * Redirect document from Prismic
 *
 * - **API ID**: `redirect`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectDocumentData>,
    "redirect",
    Lang
  >;

export type AllDocumentTypes =
  | _404Document
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LandingDocument
  | LegalsDocument
  | RedirectDocument;

/**
 * Item in *Faq → Default → Primary → Grp*
 */
export interface FaqSliceDefaultPrimaryGrpItem {
  /**
   * Question field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Button field in *Faq → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Contact
   * - **API ID Path**: faq.default.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Grp field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Faq → Variation 1 → Primary*
 */
export interface FaqSliceVariation1Primary {
  /**
   * Title field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;
}

/**
 * Variation 1 variation for Faq Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<FaqSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Faq → Variation 2 → Primary*
 */
export interface FaqSliceVariation2Primary {
  /**
   * Title field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;
}

/**
 * Variation 2 variation for Faq Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<FaqSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation =
  | FaqSliceDefault
  | FaqSliceVariation1
  | FaqSliceVariation2;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Spacer → Default → Primary*
 */
export interface SpacerSliceDefaultPrimary {
  /**
   * Size field in *Spacer → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: spacer.default.primary.choice
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  choice: prismic.SelectField<"xxl" | "xl" | "l" | "m" | "s" | "xs">;
}

/**
 * Default variation for Spacer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpacerSliceDefaultPrimary>,
  never
>;

/**
 * Line variation for Spacer Slice
 *
 * - **API ID**: `line`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSliceLine = prismic.SharedSliceVariation<
  "line",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Spacer*
 */
type SpacerSliceVariation = SpacerSliceDefault | SpacerSliceLine;

/**
 * Spacer Shared Slice
 *
 * - **API ID**: `spacer`
 * - **Description**: Spacer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpacerSlice = prismic.SharedSlice<"spacer", SpacerSliceVariation>;

/**
 * Primary content in *HeroError → Default → Primary*
 */
export interface HeroErrorSliceDefaultPrimary {
  /**
   * Image field in *HeroError → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_error.default.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Title field in *HeroError → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_error.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Button - Text field in *HeroError → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_error.default.primary.btntxt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btntxt: prismic.KeyTextField;

  /**
   * Button - Link field in *HeroError → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_error.default.primary.btnlnk
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btnlnk: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for HeroError Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroErrorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroErrorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroError*
 */
type HeroErrorSliceVariation = HeroErrorSliceDefault;

/**
 * HeroError Shared Slice
 *
 * - **API ID**: `hero_error`
 * - **Description**: HeroError
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroErrorSlice = prismic.SharedSlice<
  "hero_error",
  HeroErrorSliceVariation
>;

/**
 * Primary content in *HeroHome → Default → Primary*
 */
export interface HeroHomeSliceDefaultPrimary {
  /**
   * Title field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

/**
 * Primary content in *HeroLanding → Default → Primary*
 */
export interface HeroLandingSliceDefaultPrimary {
  /**
   * Title field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Default variation for HeroLanding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroLandingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 1 → Primary*
 */
export interface HeroLandingSliceVariation1Primary {
  /**
   * Title field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Video field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;
}

/**
 * Variation 1 variation for HeroLanding Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<HeroLandingSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 2 → Primary*
 */
export interface HeroLandingSliceVariation2Primary {
  /**
   * Title field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Input - placeholder field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your mail
   * - **API ID Path**: hero_landing.variation2.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Button - Text field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: S'abonner
   * - **API ID Path**: hero_landing.variation2.primary.btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;

  /**
   * Image field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Legals description field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.legals_dsc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legals_dsc: prismic.RichTextField;
}

/**
 * Variation 2 variation for HeroLanding Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<HeroLandingSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *HeroLanding*
 */
type HeroLandingSliceVariation =
  | HeroLandingSliceDefault
  | HeroLandingSliceVariation1
  | HeroLandingSliceVariation2;

/**
 * HeroLanding Shared Slice
 *
 * - **API ID**: `hero_landing`
 * - **Description**: HeroLanding
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSlice = prismic.SharedSlice<
  "hero_landing",
  HeroLandingSliceVariation
>;

/**
 * Primary content in *HeroLegals → Default → Primary*
 */
export interface HeroLegalsSliceDefaultPrimary {
  /**
   * Title field in *HeroLegals → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_legals.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for HeroLegals Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLegalsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroLegalsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroLegals*
 */
type HeroLegalsSliceVariation = HeroLegalsSliceDefault;

/**
 * HeroLegals Shared Slice
 *
 * - **API ID**: `hero_legals`
 * - **Description**: HeroLegals
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLegalsSlice = prismic.SharedSlice<
  "hero_legals",
  HeroLegalsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      _404Document,
      _404DocumentData,
      _404DocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      LegalsDocument,
      LegalsDocumentData,
      LegalsDocumentDataSlicesSlice,
      RedirectDocument,
      RedirectDocumentData,
      RedirectDocumentDataRedirectItem,
      AllDocumentTypes,
      FaqSlice,
      FaqSliceDefaultPrimaryGrpItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation1Primary,
      FaqSliceVariation2Primary,
      FaqSliceVariation,
      FaqSliceDefault,
      FaqSliceVariation1,
      FaqSliceVariation2,
      SpacerSlice,
      SpacerSliceDefaultPrimary,
      SpacerSliceVariation,
      SpacerSliceDefault,
      SpacerSliceLine,
      HeroErrorSlice,
      HeroErrorSliceDefaultPrimary,
      HeroErrorSliceVariation,
      HeroErrorSliceDefault,
      HeroHomeSlice,
      HeroHomeSliceDefaultPrimary,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
      HeroLandingSlice,
      HeroLandingSliceDefaultPrimary,
      HeroLandingSliceVariation1Primary,
      HeroLandingSliceVariation2Primary,
      HeroLandingSliceVariation,
      HeroLandingSliceDefault,
      HeroLandingSliceVariation1,
      HeroLandingSliceVariation2,
      HeroLegalsSlice,
      HeroLegalsSliceDefaultPrimary,
      HeroLegalsSliceVariation,
      HeroLegalsSliceDefault,
    };
  }
}
