// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  hero_error: dynamic(() => import('./HeroError')),
  hero_home: dynamic(() => import('./HeroHome')),
  hero_legals: dynamic(() => import('./HeroLegals')),
}
