// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_home: dynamic(() => import("./HeroHome")),
  hero_landing: dynamic(() => import("./HeroLanding")),
};
